# Auto-generated seed data — Featured Workouts v4 (8 picks)
# Regenerated 2026-09-12. Replaces the v3 8-pick set.
# Every workout below is real output of the app's own "Build Workout For Me"
# generator (utils/workoutGenerator.ts), run against the live exercise
# library, then hand-mapped to Wes's requested mood/flavor combos:
#   Muscle Gainer - Booty Builder / Leg Strength, Sweat - Light Weights (Full
#   Body) / Cardio, Calisthenics - Pull-Ups & Ab Work, Get Outside - Hill
#   Sprints, Build Explosion x2 (Plyometric, Loaded Power).
# Titles were shortened to drop the redundant "<Mood> - " prefix: the mood is
# already rendered as its own label directly above the title on the featured
# detail/cart screen (app/featured-workout-detail.tsx), so keeping it in the
# title too produced a visible duplicate (e.g. "Muscle gainer" / "Muscle
# Gainer - Booty Builder"). Fixed by naming these after the workout itself.
# Hero images: user-provided v4 (2026-09-12), delivered from Cloudinary
#   mood_app/featured_heroes/. optimizedImageUrl() injects f_auto,q_auto,c_limit
#   at render time.

PREVIEW_FEATURED_WORKOUTS = [
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a01",
    "title": "Booty Builder",
    "mood": "Muscle gainer",
    "duration": "60 min",
    "badge": "Build Muscle",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193572/mood_app/featured_heroes/booty_builder.jpg",
    "difficulty": "Intermediate",
    "hook": "Glutes on notice. Volume, drops, and burn from every angle.",
    "cartSizeOverride": 4,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Hip Thrust Drop Set",
        "equipment": "Hip Thruster Equipment",
        "description": "Extended thrust sets using fast load reductions",
        "battlePlan": "Instructions: Hit the reps, strip weight immediately (no rest), and keep going — the drop IS the set. 3 sets — all 3 moves in order, then rest 120s.\n3 sets\n• 8 Thrusts\n• Thrust drop → 8\n• Thrust drop → 8\nRest 120s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240654/mood_app/workout_images/60kuhstx_hip_thrust.jpg",
        "intensityReason": "Drop sets extend time under tension for hypertrophy",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Glutes",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "flash",
            "title": "Immediate drops",
            "description": "Reduce load ~25% without resting.",
          },
          {
            "icon": "construct",
            "title": "Same mechanics",
            "description": "Range and tempo stay identical.",
          },
          {
            "icon": "flame",
            "title": "Chase deep burn",
            "description": "Continuous tension is goal.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Pause Kickback",
        "equipment": "Glute Kick Machine",
        "description": "Strict tempo isolates stronger contraction at end",
        "battlePlan": "Instructions: Own the lowering — count the seconds down, then move normally on the way up. Dead-stop pause — kill all momentum at the pause point before finishing the rep. 3 sets of 8 per side — rest 90s between sets, take all of it.\n3 sets\n• 8 per leg Pause Kickbacks\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241397/mood_app/workout_images/k5zii6kf_download_8_.jpg",
        "intensityReason": "Added pause loads glute contraction maximally",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Glutes",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "timer",
            "title": "Pause 2s with knee extended back",
            "description": "Extended pause maximizes peak contraction and muscle activation.",
          },
          {
            "icon": "construct",
            "title": "Slow return; avoid pad snapping",
            "description": "Controlled eccentric enhances muscle development and joint safety.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 2,
        "name": "Cable High Kickback",
        "equipment": "Single Stack Cable Machine",
        "description": "Top‑end contraction isolates and strengthens glutes",
        "battlePlan": "Instructions: Own the lowering — count the seconds down, then move normally on the way up. Dead-stop pause — kill all momentum at the pause point before finishing the rep. 3 sets of 8–10 per side — rest 75–90s between sets, take all of it.\n3 sets\n• 8–10 per leg Kickbacks (2s pause top)\nRest 75–90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241390/mood_app/workout_images/coxrp5yp_gk.jpg",
        "intensityReason": "Kickbacks with higher angle add peak glute tension",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Glutes",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "construct",
            "title": "Ankle cuff, pulley low, hinge slightly forward",
            "description": "Low pulley position creates optimal resistance curve for glutes.",
          },
          {
            "icon": "timer",
            "title": "Kick upward + back, pause two seconds top",
            "description": "Pause at peak contraction maximizes muscle activation and control.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 3,
        "name": "Banded Abduction",
        "equipment": "Hip Abductor Machine",
        "description": "Combo band+machine emphasizes hypertrophy work",
        "battlePlan": "Instructions: 4 sets of 12 — rest 90s between sets, take all of it.\n4 sets\n• 12 Banded Abductions\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241400/mood_app/workout_images/o6mep0pr_ha.jpg",
        "intensityReason": "Band tension increases abductor contraction top end",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Glutes",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "resize",
            "title": "Strap band above knees, press outward",
            "description": "Band creates additional resistance throughout the range of motion.",
          },
          {
            "icon": "construct",
            "title": "Keep knees wide, resist on way in",
            "description": "Controlled return prevents band snap-back and maintains tension.",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a02",
    "title": "Leg Day Strength",
    "mood": "Muscle gainer",
    "duration": "75 min",
    "badge": "Lift Heavy",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193577/mood_app/featured_heroes/leg_strength.jpg",
    "difficulty": "Intermediate",
    "hook": "Heavy compounds, low reps. Build real leg strength.",
    "cartSizeOverride": 5,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Sissy Squat 1½ Reps",
        "equipment": "Barbell",
        "description": "High tension squatting style grows endurance fast",
        "battlePlan": "Instructions: Sink to the bottom, drive halfway up, sink back down, then stand tall — that's ONE rep. The half rep stays in the bottom, where it burns. 3 sets of 8 — rest 90s between sets, take all of it.\n3 sets\n• 8 Combo Reps (half + full = 1)\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://customer-assets.emergentagent.com/job_ac961e42-7fcc-4980-8c0c-d7055d6cef31/artifacts/fwtkmsgm_bb%20sissy%20squat%202.png",
        "intensityReason": "Half+full rep sequence lengthens quad activation",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Quads",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "refresh",
            "title": "Perform half rep, then full as one",
            "description": "Complex rep pattern extends time under tension for quads.",
          },
          {
            "icon": "construct",
            "title": "Keep bar tight, don't roll forward",
            "description": "Maintain bar position and posture throughout complex movement.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Heavy Extensions",
        "equipment": "Leg Extension Machine",
        "description": "Machine allows safe overload using strict form",
        "battlePlan": "Instructions: 4 sets of 8–10 — rest 90s between sets, take all of it.\n4 sets\n• 8–10 Heavy Extensions\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240641/mood_app/workout_images/er89oli2_download_23_.jpg",
        "intensityReason": "Progressive heavy loading maximizes quad growth",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Quads",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "fitness",
            "title": "Grip handles tight to stabilize",
            "description": "Secure grip maintains stability for heavy quad extensions.",
          },
          {
            "icon": "flash",
            "title": "Drive pad up forceful, control back",
            "description": "Explosive concentric with controlled eccentric builds strength.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 2,
        "name": "1½ Rep Leg Extensions",
        "equipment": "Leg Extension Machine",
        "description": "Longer muscle strain increases hypertrophy response",
        "battlePlan": "Instructions: Every rep = one full rep plus a half rep in the hardest range before you finish. 3 sets of 8–10 — rest 90s between sets, take all of it.\n3 sets\n• 8–10 Total Combo Reps\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240639/mood_app/workout_images/6hwlna7o_quad_ext.jpg",
        "intensityReason": "Half+full rep cycle expands quad time under load",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Quads",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "refresh",
            "title": "Perform one half + one full rep",
            "description": "Complex rep pattern extends time under tension significantly.",
          },
          {
            "icon": "construct",
            "title": "Keep tempo smooth, don't drop pad",
            "description": "Controlled movement maintains tension throughout range.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 3,
        "name": "Barbell Pause RDL",
        "equipment": "Barbell",
        "description": "Strict hold eliminates momentum, builds hamstring size",
        "battlePlan": "Instructions: Own the lowering — count the seconds down, then move normally on the way up. Dead-stop pause — kill all momentum at the pause point before finishing the rep. 4 sets of 8 — rest 90s between sets, take all of it.\n4 sets\n• 8 RDLs (2s pause at shin)\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240638/mood_app/workout_images/46ki5rsl_download_15_.jpg",
        "intensityReason": "Mid‑hinge pause increases hamstring strength time",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Hamstrings",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "timer",
            "title": "Pause 2s across shin level",
            "description": "Isometric hold at stretched position builds strength.",
          },
          {
            "icon": "construct",
            "title": "Keep bar tight against body always",
            "description": "Close bar path maintains hamstring tension throughout.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 4,
        "name": "Heavy Leg Curl",
        "equipment": "Leg Curl Machine",
        "description": "Increased weight overload boosts hypertrophy",
        "battlePlan": "Instructions: 4 sets of 8–10 — rest 90s between sets, take all of it.\n4 sets\n• 8–10 Heavy Curls\nRest 90s",
        "duration": "14–16 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240637/mood_app/workout_images/3vkyuj1o_download_19_.jpg",
        "intensityReason": "Progressive loading builds hamstrings thickness",
        "difficulty": "intermediate",
        "workoutType": "Muscle Building - Hamstrings",
        "moodCard": "Muscle gainer",
        "moodTips": [
          {
            "icon": "shield",
            "title": "Brace core firm, pad curl explosive",
            "description": "Core stability allows maximum force transfer to hamstrings.",
          },
          {
            "icon": "flash",
            "title": "Finish with hard squeeze up top",
            "description": "Peak contraction at top maximizes muscle activation.",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a03",
    "title": "Full Body Light & Fast",
    "mood": "Sweat / Burn Fat",
    "duration": "32 min",
    "badge": "Resistance",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193587/mood_app/featured_heroes/sweat_light_weights.jpg",
    "difficulty": "Intermediate",
    "hook": "Light loads, quick pace. A full-body burn that never gets heavy.",
    "cartSizeOverride": 2,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "EMOM 12 (BB)",
        "equipment": "Barbells",
        "description": "Odd minutes thrusters; even minutes sumo high pulls.",
        "battlePlan": "Instructions: Work for 12 minutes, alternating each minute.\n• Odd min, 8 Thrusters\n• Even min, 10 Sumo Deadlift High Pulls",
        "duration": "12 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241370/mood_app/workout_images/2tl6mdrg_download.jpg",
        "intensityReason": "Alternating minutes sharpen cadence and repeatability.",
        "difficulty": "intermediate",
        "workoutType": "Weights Only",
        "moodCard": "Sweat / Burn Fat",
        "moodTips": [
          {
            "icon": "fitness",
            "title": "Thrusters: rebound into press",
            "description": "Use squat momentum to power the overhead press",
          },
          {
            "icon": "trending-up",
            "title": "High pulls: elbows high, bar close",
            "description": "Lead with elbows and keep bar traveling close to body",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Sprint Intervals",
        "equipment": "Sled",
        "description": "Ten rounds: 10 m sprint push, walk back recovery pacing.",
        "battlePlan": "Instructions: Own the lowering — count the seconds down, then move normally on the way up. Sprint at max effort, then walk the FULL recovery — showing up fresh for every rep is the whole workout. 10 sets of ~10m — rest walk back slow between sets, take all of it.\nPerform 10 rounds:\n• Sprint Push — ~10m\nRest: walk back slow",
        "duration": "20 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241377/mood_app/workout_images/k6ha38p9_download_1_.jpg",
        "intensityReason": "Short sprint pushes spike power with full walkback rest.",
        "difficulty": "intermediate",
        "workoutType": "Weights Only",
        "moodCard": "Sweat / Burn Fat",
        "moodTips": [
          {
            "icon": "flash",
            "title": "Explode with leg drive",
            "description": "Push forcefully through ground with each step",
          },
          {
            "icon": "walk",
            "title": "Keep stride short and quick",
            "description": "Use rapid choppy steps for maximum power output",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a04",
    "title": "Cardio Blast",
    "mood": "Sweat / Burn Fat",
    "duration": "33 min",
    "badge": "Conditioning",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193585/mood_app/featured_heroes/sweat_cardio.jpg",
    "difficulty": "Intermediate",
    "hook": "Jump rope to elliptical. Pure cardio, smartly paced.",
    "cartSizeOverride": 2,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Combo Jumps",
        "equipment": "Jump rope",
        "description": "Combination jumping patterns with basic,\nalternate foot, and double bounce styles.\n ",
        "battlePlan": "Instructions: 4 rounds — follow the 4 timed segments in order, no skipping.\n• 1 min basic jump\n• 30 sec alternate foot\n• 30 sec double bounce\n• 1 min rest",
        "duration": "15 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240959/mood_app/workout_images/vj88wh1r_download.jpg",
        "intensityReason": "Multiple jumping patterns challenge intermediate coordination.",
        "difficulty": "intermediate",
        "workoutType": "Cardio Only",
        "moodCard": "Sweat / Burn Fat",
        "moodTips": [
          {
            "icon": "body",
            "title": "Soft Landing",
            "description": "Land softly to protect shins and joints.",
          },
          {
            "icon": "flash",
            "title": "Efficient Turns",
            "description": "Use short, efficient rope turns; minimize arm movement.",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Reverse & Forward",
        "equipment": "Elliptical",
        "description": "Forward and reverse elliptical intervals\nwith sprint finishes for muscle balance.\n ",
        "battlePlan": "Instructions: Cap every set with the finisher: 2 min easy — it counts, don't skip it. 4 rounds — follow the 3 timed segments in order, no skipping.\n• 3 min forward (resistance 6)\n• 2 min reverse (resistance 4)\n• 1 min sprint (forward, resistance 5)\n• finish with 2 min easy",
        "duration": "18 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240936/mood_app/workout_images/0knopdsq_download_3_.jpg",
        "intensityReason": "Direction changes engage muscles with cardio demand.",
        "difficulty": "intermediate",
        "workoutType": "Cardio Only",
        "moodCard": "Sweat / Burn Fat",
        "moodTips": [
          {
            "icon": "body",
            "title": "Core Control",
            "description": "Core tight, avoid knee overextension in reverse.",
          },
          {
            "icon": "refresh",
            "title": "Direction Switch",
            "description": "Exhale fully when switching direction to reset rhythm.",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a05",
    "title": "Pull-Up & Core Builder",
    "mood": "Calisthenics",
    "duration": "82 min",
    "badge": "Pull",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193576/mood_app/featured_heroes/calisthenics.jpg",
    "difficulty": "Intermediate",
    "hook": "Pull-up bar and ab wheel. Build real pulling strength.",
    "cartSizeOverride": 4,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Eccentric Lines",
        "equipment": "Pull up bar",
        "description": "Chin-up eccentrics, isometric holds, knee raises.",
        "battlePlan": "Instructions: Own the lowering — count the seconds down, then move normally on the way up. The hold is strict: locked position, squeezing hard, no drifting. Work top to bottom.\nEccentric Chin-Up\n• 4 × 3–4 (RPE 5–6), 90s rest\nTop Isometric Pullup Hold (chin over bar)\n• 3 × 10–15s (RPE 5), 75s rest\nHanging Knee Raise\n• 3 × 10–12 (RPE 5), 60s rest",
        "duration": "22–28 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241201/mood_app/workout_images/7475d60t_chin_ups.jpg",
        "intensityReason": "Negatives build strength through full, safe range.",
        "difficulty": "intermediate",
        "workoutType": "Calisthenics",
        "moodCard": "Calisthenics",
        "moodTips": [
          {
            "icon": "body",
            "title": "4–5s negatives",
            "description": "4–5s negatives",
          },
          {
            "icon": "body",
            "title": "Hold chest-up position",
            "description": "Hold chest-up position",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Wheel Lines",
        "equipment": "Ab wheel",
        "description": "Kneeling rolls fuller range, hollow rocks to polish.",
        "battlePlan": "Instructions: Complete ALL reps on one side before switching — no alternating unless written. Every rep at full intent — reset your stance between reps; speed beats load. Work top to bottom.\nKneeling Ab Wheel (fuller ROM)\n• 4 × 6–8 (RPE 5), 90s rest\nHollow Rock\n• 3 × 10–15 (RPE 5), 60s rest\nSide Plank with Hip Tap\n• 3 × 8–10/side (RPE 5), 45–60s rest",
        "duration": "14–18 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241241/mood_app/workout_images/pgkoxn00_download.jpg",
        "intensityReason": "Moderate volume kneeling rolls challenge midline.",
        "difficulty": "intermediate",
        "workoutType": "Calisthenics",
        "moodCard": "Calisthenics",
        "moodTips": [
          {
            "icon": "body",
            "title": "Smooth 3s lowers",
            "description": "Control the eccentric for 3 seconds to maximize tension",
          },
          {
            "icon": "leaf",
            "title": "Exhale pulling back",
            "description": "Breathe out forcefully during concentric to aid core stability",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 2,
        "name": "Volume Pull",
        "equipment": "Pull up bar",
        "description": "Assisted pullups, inverted rows, hollow rocks finish.",
        "battlePlan": "Instructions: Every rep at full intent — reset your stance between reps; speed beats load. Match the RPE, not a number on the bar — RPE 7 means 3 clean reps left in the tank. Work top to bottom.\nBand-Assisted Pullup\n• 4 × 6–8 (RPE 5), 90s rest\nInverted Row (feet flat)\n• 4 × 8–10 (RPE 5), 75s rest\nHollow Rock\n• 3 × 10–15 (RPE 5), 60s rest",
        "duration": "22–28 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241216/mood_app/workout_images/cvdrz3i5_inverted_rows.jpg",
        "intensityReason": "Moderate band assist allows higher-quality volume.",
        "difficulty": "intermediate",
        "workoutType": "Calisthenics",
        "moodCard": "Calisthenics",
        "moodTips": [
          {
            "icon": "body",
            "title": "Smooth 2–1–3 tempo",
            "description": "Smooth 2–1–3 tempo",
          },
          {
            "icon": "body",
            "title": "Keep ribs down in rocks",
            "description": "Keep ribs down in rocks",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 3,
        "name": "Hanging Leg Raise",
        "equipment": "Pull-Up Bar (abs)",
        "description": "Straight-leg raises increasing lower ab strength and tension",
        "battlePlan": "Instructions: 4 sets of 10–12 — rest 75s between sets, take all of it.\n4 sets\n• 10–12 reps\nRest 75s",
        "duration": "10–12 min",
        "imageUrl": "https://customer-assets.emergentagent.com/job_ac961e42-7fcc-4980-8c0c-d7055d6cef31/artifacts/btrm5pgt_pull%20up%20bar%20leg%20raise.png",
        "intensityReason": "Straight legs lengthen the lever and overload the lower abs",
        "difficulty": "intermediate",
        "workoutType": "Calisthenics",
        "moodCard": "Calisthenics",
        "moodTips": [
          {
            "icon": "remove",
            "title": "Keep legs as straight as possible",
            "description": "Bent knees reduce the challenge significantly.",
          },
          {
            "icon": "arrow-up",
            "title": "Lift from your pelvis, not hips alone",
            "description": "Posterior tilt fully engages the abs.",
          },
          {
            "icon": "flame",
            "title": "The burn should build gradually",
            "description": "Especially in the lower abs.",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a06",
    "title": "Hill Sprints",
    "mood": "Get Outside",
    "duration": "44 min",
    "badge": "Explosive",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193582/mood_app/featured_heroes/outdoor_hill_run.jpg",
    "difficulty": "Intermediate",
    "hook": "Find a hill. Sprint it. Repeat until it hurts.",
    "cartSizeOverride": 2,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Hill Power Mix",
        "equipment": "Hills",
        "description": "Powerful jumps plus sprints develop rhythm and drive uphill.",
        "battlePlan": "Instructions: Uphill bounds: walk down. Uphill skips for height: walk down. Uphill sprints: walk down. Work top to bottom.\n• Uphill Bounds — 6 × (12–15)\n• Uphill Skips For Height — 6 × (~25–30yd)\n• Uphill Sprints — 6 × (~25–30yd)",
        "duration": "18–24 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240859/mood_app/workout_images/zqqramht_download_13_.jpg",
        "intensityReason": "Bounds, skips, sprints build elastic strength safely.",
        "difficulty": "intermediate",
        "workoutType": "Outdoor",
        "moodCard": "Get Outside",
        "moodTips": [
          {
            "icon": "trending-up",
            "title": "Bounds: knee drive then hip extend; stick landings under control",
            "description": "Drive knee high, extend hip fully, and land with stability",
          },
          {
            "icon": "walk",
            "title": "Avoid heel striking uphill; keep cadence snappy and forward",
            "description": "Land on midfoot with quick turnover for uphill efficiency",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Strength Endurance Mix",
        "equipment": "Hills",
        "description": "Lunges, broad jumps, sprints reinforce controlled power.",
        "battlePlan": "Instructions: Sprint at max effort, then walk the FULL recovery — showing up fresh for every rep is the whole workout. Every rep at full intent — reset your stance between reps; speed beats load. 6 rounds — all 3 moves in order.\n• 6 rounds:\n\n• Uphill Walking Lunges — ~20yd\n6–8 uphill broad jumps (~20 yd)\n• Uphill Sprint — ~20yd\nWalk down recovery",
        "duration": "20–26 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240856/mood_app/workout_images/xyu6atdo_download_10_.jpg",
        "intensityReason": "Lunges and jumps pre-fatigue, then sprints build posture.",
        "difficulty": "intermediate",
        "workoutType": "Outdoor",
        "moodCard": "Get Outside",
        "moodTips": [
          {
            "icon": "body",
            "title": "Lunges: knee over mid-foot; upright torso; no inward collapse",
            "description": "Align knee with foot center while staying tall without knee cave",
          },
          {
            "icon": "trending-up",
            "title": "Broad jumps: swing arms; land softly; stabilize before sprint",
            "description": "Use arm momentum, absorb landing, then set before running",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a07",
    "title": "Plyo Power",
    "mood": "Build Explosion",
    "duration": "33 min",
    "badge": "Jump & Bound",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193573/mood_app/featured_heroes/build_explosion_box_jumps.jpg",
    "difficulty": "Intermediate",
    "hook": "Jump, land, reset. Train explosive power the athlete way.",
    "cartSizeOverride": 3,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Depth Drop Rebound",
        "equipment": "Plyo Box",
        "description": "Drop down, stick one second hold, then rebound to box immediately",
        "battlePlan": "Instructions: Superset: the paired moves run back-to-back with zero rest — rest only after the pair. Every rep at full intent — reset your stance between reps; speed beats load. 4 sets of 3 — rest 90s between sets, take all of it.\n4 sets\n• 3 Depth Drop (stick 1s) → Rebound to Box\nRest 90s",
        "duration": "10–12 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240617/mood_app/workout_images/ofqstfu6_download_1_.jpg",
        "intensityReason": "Eccentric stick then rapid takeoff improves force development rate",
        "difficulty": "intermediate",
        "workoutType": "Build Explosion - Body Weight",
        "moodCard": "Build Explosion",
        "moodTips": [
          {
            "icon": "body",
            "title": "Landing Position",
            "description": "Heels kiss; knees soft; hips back",
          },
          {
            "icon": "flash",
            "title": "Rebound Timing",
            "description": "Rebound immediately after stick",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "DB Broad Jump Carry",
        "equipment": "Dumbbells",
        "description": "Two broad jumps; grab DBs; fast upright ten-meter carry.",
        "battlePlan": "Instructions: Every rep at full intent — reset your stance between reps; speed beats load. 4 sets of 2 — rest 90s between sets, take all of it.\n4 sets\n• 2 Broad Jumps (stick) → 10m Farmer Carry\nRest 90s",
        "duration": "10–12 min",
        "imageUrl": "https://customer-assets.emergentagent.com/job_muscle-mapper-2/artifacts/yclz6917_dbbjc.avif",
        "intensityReason": "Jumps then loaded carry train projection and bracing.",
        "difficulty": "intermediate",
        "workoutType": "Build Explosion - Weight Based",
        "moodCard": "Build Explosion",
        "moodTips": [
          {
            "icon": "walk",
            "title": "Jumps",
            "description": "Jumps: big arms; stick one to two seconds; measure",
          },
          {
            "icon": "body",
            "title": "Carry",
            "description": "Carry: posture tall; short, fast steps; firm grip",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 2,
        "name": "Box Jump Repeats",
        "equipment": "Plyo Box",
        "description": "Crisp consecutive jumps with short resets to preserve power output",
        "battlePlan": "Instructions: Every rep at full intent — reset your stance between reps; speed beats load. 4 sets of 6–8 — rest 75s between sets, take all of it.\n4 sets\n• 6–8 Box Jumps\nRest 75s",
        "duration": "10–12 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770240628/mood_app/workout_images/wok1mz8a_rbj.jpg",
        "intensityReason": "Repeated jump efforts build sustainable explosive power capacity",
        "difficulty": "intermediate",
        "workoutType": "Build Explosion - Body Weight",
        "moodCard": "Build Explosion",
        "moodTips": [
          {
            "icon": "refresh",
            "title": "Reset",
            "description": "Reset stance and breath each rep",
          },
          {
            "icon": "speedometer",
            "title": "Consistency",
            "description": "Match height and landing each time",
          },
        ],
      },
    ],
  },
  {
    "_id": "6b0a11f0a1b2c3d4e5f60a08",
    "title": "Loaded Power",
    "mood": "Build Explosion",
    "duration": "22 min",
    "badge": "Weighted",
    "heroImageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1789193574/mood_app/featured_heroes/build_explosion_hang_clean.jpg",
    "difficulty": "Intermediate",
    "hook": "Load it heavy, move it fast. Strength meets speed.",
    "cartSizeOverride": 2,
    "exercises": [
      {
        "exerciseId": "",
        "order": 0,
        "name": "Clean to Jerk",
        "equipment": "Kettlebells",
        "description": "Pop to rack; dip-drive; punch under; stable overhead stick.",
        "battlePlan": "Instructions: Complete ALL reps on one side before switching — no alternating unless written. Every rep at full intent — reset your stance between reps; speed beats load. 4 sets of 4 per side — rest 90s between sets, take all of it.\n4 sets\n• 4 per side Clean → Jerk\nRest 90s",
        "duration": "10–12 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241149/mood_app/workout_images/gxkmxo9y_download_6_.jpg",
        "intensityReason": "Clean primes rack; jerk expresses rapid vertical force.",
        "difficulty": "intermediate",
        "workoutType": "Build Explosion - Weight Based",
        "moodCard": "Build Explosion",
        "moodTips": [
          {
            "icon": "fitness",
            "title": "Rack",
            "description": "Rack thumb in; elbow down/in; wrist neutral",
          },
          {
            "icon": "arrow-up",
            "title": "Jerk",
            "description": "Dip shallow; soft land; lock elbows solid",
          },
        ],
      },
      {
        "exerciseId": "",
        "order": 1,
        "name": "Trap Bar High Pull",
        "equipment": "Trap Hex Bar",
        "description": "Pop tall; elbows drive up; keep handle path tight and close.",
        "battlePlan": "Instructions: 4 sets of 2 — rest 90s between sets, take all of it.\n4 sets\n• 4 × 2 High Pulls (moderate)\nRest 90s",
        "duration": "10–12 min",
        "imageUrl": "https://res.cloudinary.com/dfsygar5c/image/upload/v1770241148/mood_app/workout_images/gur5s8sa_tbhp.jpg",
        "intensityReason": "Aggressive extension elevates handles with rapid speed.",
        "difficulty": "intermediate",
        "workoutType": "Build Explosion - Weight Based",
        "moodCard": "Build Explosion",
        "moodTips": [
          {
            "icon": "flash",
            "title": "Pull",
            "description": "Hinge load; sweep close; full triple extension timing",
          },
          {
            "icon": "arrow-up",
            "title": "Finish",
            "description": "Elbows up/back; avoid early curl; reset between reps",
          },
        ],
      },
    ],
  },
]

# The exact order of featured workout IDs for the carousel
# (seed-time stable _ids; auto-seed regenerates real ObjectIds at startup.)
FEATURED_WORKOUT_IDS = [
    "6b0a11f0a1b2c3d4e5f60a01",  # Booty Builder
    "6b0a11f0a1b2c3d4e5f60a02",  # Leg Day Strength
    "6b0a11f0a1b2c3d4e5f60a03",  # Full Body Light & Fast
    "6b0a11f0a1b2c3d4e5f60a04",  # Cardio Blast
    "6b0a11f0a1b2c3d4e5f60a05",  # Pull-Up & Core Builder
    "6b0a11f0a1b2c3d4e5f60a06",  # Hill Sprints
    "6b0a11f0a1b2c3d4e5f60a07",  # Plyo Power
    "6b0a11f0a1b2c3d4e5f60a08",  # Loaded Power
]
