// AUTO-GENERATED from data/*-data.ts plan tags, audited by tools/audit_tags.js.
// Wrong-video tags were dropped; ambiguous ones kept but flagged in the review.
export const TUTORIAL_MAP: Record<string, string> = {
  "1 20 25m weighted rope pull": "pull_ups",
  "1 20m heavy rope pull": "pull_ups",
  "1 rep db rdl combo": "db_rdl",
  "1 rep sit up": "sit_ups",
  "10m push 10m pull": "pull_ups",
  "10m push 10m pull 10m push": "pull_ups",
  "15m sled push": "sled_push",
  "2 2 clean pulls": "kb_clean",
  "2 2 trap bar jumps": "trap_bar_squat_jump",
  "20 25m harness pull": "pull_ups",
  "3 3 banded jump squats": "kb_squat",
  "3 3 jump squats": "landmine_hack_squat_jump",
  "4 5m sled push 15s between efforts": "sled_push",
  "4 amrap chin ups": "chin_ups",
  "4 amrap close grip chin ups": "chin_ups",
  "4 amrap dips": "dips",
  "45 back extension": "roman_chair_weighted_back_extension",
  "5 amrap chin ups": "chin_ups",
  "6 8 1 rep trap bar squats": "trap_bar_squat_jump",
  "6 squat jump press": "kb_squat",
  "8 10m sled push": "sled_push",
  "abductions": "hip_abductor",
  "alternating dumbbell curl": "dumbbell_curl",
  "alternating hanging knee raise": "hanging_knee_raise",
  "alternating reverse lunge": "barbell_reverse_lunge",
  "alternating snatch": "bb_snatch",
  "alternating snatches": "bb_snatch",
  "alternating waves": "battle_rope_alternating_waves",
  "archer pull ups": "pull_ups",
  "arms overhead sit ups": "sit_ups",
  "arnold press": "db_arnold_press",
  "assisted bodyweight dips": "assisted_dips",
  "assisted chin ups": "chin_ups",
  "assisted dip eccentric": "assisted_dips",
  "assisted dips": "assisted_dips",
  "assisted neutral pull ups": "neutral_grip_assisted_pull_up",
  "assisted pull ups": "wide_grip_assisted_pull_up",
  "back extension": "roman_chair_back_extension",
  "back extensions": "roman_chair_back_extension",
  "back rack jump squats": "kb_squat",
  "back squat 1 5 reps": "smith_machine_back_squat",
  "back squat burnout": "kb_squat",
  "back squat pause reps": "kb_squat",
  "back squat pulses": "kb_squat",
  "back squats": "smith_machine_back_squat",
  "backward pull": "pull_ups",
  "ball slams": "slam_ball_slams",
  "band assisted dips": "assisted_dips",
  "band pull aparts": "pull_ups",
  "band squat jumps": "kb_squat",
  "banded jump squats": "kb_squat",
  "banded squats": "kb_squat",
  "barbell bench press": "barbell_flat_bench_press",
  "barbell bent over row": "barbell_row",
  "barbell calf raise": "calf_raise",
  "barbell calf raise drop set": "calf_raise",
  "barbell calf raise elevated": "calf_raise",
  "barbell calf raise iso jumps": "calf_raise",
  "barbell calf raise tempo": "calf_raise",
  "barbell clean pull": "kb_clean",
  "barbell deadlift": "barbell_deadlift",
  "barbell good morning": "barbell_good_mornings",
  "barbell hack squats": "hack_squat",
  "barbell high pull": "kb_high_pull",
  "barbell lunge burnout": "barbell_lunge",
  "barbell power clean": "power_clean",
  "barbell rdls": "barbell_rdl",
  "barbell row": "barbell_row",
  "barbell row drop set": "barbell_row",
  "barbell standing calf raise": "calf_raise",
  "barbell static lunge": "barbell_split_squat",
  "barbell tempo calf raise": "calf_raise",
  "barbell walking lunge": "barbell_lunge",
  "barbell walking lunge drop set": "barbell_lunge",
  "bench dips": "bench_dips",
  "bench press": "barbell_flat_bench_press",
  "bench rows": "barbell_row",
  "bent over row": "barbell_row",
  "bent over rows": "barbell_row",
  "bird dog": "bird_dog",
  "bird dogs": "bird_dog",
  "bodyweight dips": "bench_dips",
  "bodyweight good morning": "barbell_good_mornings",
  "bodyweight hip thrusts": "barbell_hip_thrust",
  "bodyweight jump squat": "kb_goblet_jump_squat",
  "bodyweight squat": "kb_squat",
  "box back squat": "kb_squat",
  "box back squats": "kb_squat",
  "box bench dips": "bench_dips",
  "box goblet squats": "kb_goblet_squat",
  "box jumps": "plyo_box_jump",
  "bulgarian split squat": "db_bulgarian_split_squat",
  "bulgarian split squats per leg": "db_bulgarian_split_squat",
  "burpees": "burpee_box_jump",
  "cable assisted squat hold": "cable_squat",
  "cable crunch": "crunches",
  "cable curl": "cable_straight_bar_curl",
  "cable extensions": "cable_overhead_tricep_extension",
  "cable face pull": "cable_face_pull",
  "cable fly": "cable_machine_fly",
  "cable front raise": "db_front_raise",
  "cable goblet squat": "cable_squat",
  "cable goblet squats": "cable_squat",
  "cable lateral raise": "cable_lateral_raise",
  "cable pull through": "cable_pull_through",
  "cable rdls": "db_rdl",
  "cable rear delt fly": "cable_rear_delt_fly",
  "cable rows": "cable_rope_row",
  "cable split squats per leg": "cable_squat",
  "cable squats": "cable_squat",
  "cable y raise": "cable_lateral_raise",
  "calf press": "calf_raise",
  "calf raise machine": "calf_raise",
  "calf raise machine drop set": "calf_raise",
  "calf raise machine iso jumps": "calf_raise",
  "chain box squat speed sets": "kb_squat",
  "chest passes": "slam_ball_chest_pass",
  "chest supported db rows": "chest_supported_db_row",
  "chest supported dumbbell row": "chest_supported_db_row",
  "chest supported row": "t-bar_row_machine",
  "chest supported row machine": "chest_supported_db_row",
  "chest to bar pull ups": "pull_ups",
  "chin ups": "chin_ups",
  "clamshells l": "clamshells",
  "clamshells r": "clamshells",
  "clean": "kb_clean",
  "clean pulls": "kb_clean",
  "clean push press": "kb_clean",
  "clean thrusters": "kb_clean",
  "cleans": "kb_clean",
  "close grip bench press": "close_grip_bench_press",
  "close grip ez press": "close_grip_bench_press",
  "commando pull ups": "pull_ups",
  "controlled back squat": "kb_squat",
  "controlled barbell reverse lunge": "barbell_reverse_lunge",
  "crunches": "crunches",
  "crunches 10s hold": "crunches",
  "crunches hold": "crunches",
  "db calf raise drop set": "calf_raise",
  "db calf raise iso jumps": "calf_raise",
  "db flat press": "dumbbell_flat_bench_press",
  "db good mornings": "barbell_good_mornings",
  "db incline press": "dumbbell_incline_press",
  "db overhead extensions": "cable_overhead_tricep_extension",
  "db rdls": "db_rdl",
  "db rows": "db_single_arm_row",
  "db skullcrushers": "db_skull_crusher",
  "db squats": "kb_squat",
  "deadlift": "barbell_deadlift",
  "deadlift style trap bar squats": "kb_squat",
  "deadlifts": "barbell_deadlift",
  "decline barbell press": "decline_bench_press",
  "decline crunches": "crunches",
  "decline press": "decline_bench_press",
  "decline sit ups": "sit_ups",
  "deficit barbell rdls": "barbell_rdl",
  "deficit db rdls": "db_rdl",
  "deficit rdls": "db_rdl",
  "depth step rebound to box": "depth_step_rebound",
  "dip drop ladder": "dips",
  "dips": "dips",
  "double kb row": "kb_gorilla_rows",
  "double kb rows": "kb_gorilla_rows",
  "double swings": "kb_double_swing",
  "dumbbell curl": "dumbbell_curl",
  "dumbbell lateral raise": "dumbbell_lateral_raise",
  "dumbbell rdls": "db_rdl",
  "dumbbell single leg calf raise": "calf_raise",
  "dumbbell supported calf raise": "calf_raise",
  "easy glide pulls": "pull_ups",
  "eccentric chin up": "chin_ups",
  "even 20s hollow hold then lunges till minute": "hollow_holds",
  "even min 10 sumo deadlift high pulls": "kb_high_pull",
  "even min 12 alternating renegade rows": "db_renegade_rows",
  "everse lunges per leg": "barbell_reverse_lunge",
  "explosive rope slams": "battle_rope_slams",
  "ez bar curl": "ez_bar_curl",
  "ez curl": "ez_bar_curl",
  "ez skullcrushers": "ez_bar_skull_crusher",
  "face pull": "cable_face_pull",
  "face pulls": "cable_face_pull",
  "flat bench crunches": "crunches",
  "forearm plank": "plank",
  "front foot elevated barbell lunge": "barbell_lunge",
  "front hold sissy squats": "db_front_squat",
  "front lever reps": "8DA3DEBF-82F9-4F0B-8DA3-ED68283A1BC8",
  "front plank": "plank",
  "front squat": "barbell_front_squat",
  "front squat 1 5 reps": "barbell_front_squat",
  "front squats": "barbell_front_squat",
  "glute biased back squat": "kb_squat",
  "glute bridge": "glute_bridge",
  "goblet jump squats": "kb_goblet_jump_squat",
  "goblet squat": "kb_squat",
  "goblet squat 1 5 reps": "dumbbell_goblet_squat",
  "goblet squat jumps": "kb_goblet_jump_squat",
  "goblet squat tempo": "kb_squat",
  "goblet squats": "kb_squat",
  "good morning reps": "barbell_good_mornings",
  "good mornings": "barbell_good_mornings",
  "gorilla row": "kb_gorilla_rows",
  "gorilla rows": "kb_gorilla_rows",
  "hack squat": "hack_squat",
  "hack squat jumps": "landmine_hack_squat_jump",
  "hack squats": "hack_squat",
  "hammer curl": "dumbbell_hammer_curl",
  "hammer curls": "dumbbell_hammer_curl",
  "hang clean pulls": "hang_clean",
  "hang cleans": "hang_clean",
  "hang power cleans": "power_clean",
  "hanging knee raise": "hanging_knee_raise",
  "hanging knee raise hold": "hanging_knee_raise",
  "hanging l sit raise": "sit_ups",
  "hanging leg raise": "hanging_toe_touch",
  "hanging leg raise bar": "hanging_toe_touch",
  "heavy cable front squats": "cable_squat",
  "heavy crunches": "crunches",
  "heavy db rows": "db_single_arm_row",
  "heavy glute back squat": "kb_squat",
  "heavy hip thrust pause": "barbell_hip_thrust",
  "heavy hip thrusts": "barbell_hip_thrust",
  "heavy kb push press": "landmine_push_press",
  "heavy two hand swings": "kb_double_swing",
  "heel elevated front squat pause": "db_front_squat",
  "high cable row": "cable_face_pull",
  "high plank shoulder taps": "plank",
  "high pulls": "kb_high_pull",
  "high pulls from blocks": "kb_high_pull",
  "high to low cable fly": "cable_fly_high_to_low",
  "hip abduction": "hip_abductor",
  "hip thrust drop set": "barbell_hip_thrust",
  "hip thrust pulse reps": "barbell_hip_thrust",
  "hip thrusts": "barbell_hip_thrust",
  "hollow hold": "hollow_holds",
  "hollow rock": "hollow_holds",
  "incline barbell press": "barbell_incline_bench_press",
  "incline cable curl": "incline_db_curl",
  "incline cable fly": "cable_fly_low_to_high",
  "incline db curl": "incline_db_curl",
  "incline dumbbell curl": "incline_db_curl",
  "incline dumbbell delt fly": "incline_db_fly",
  "incline dumbbell lateral raise": "incline_bench_lat_t_raise",
  "incline press": "barbell_incline_bench_press",
  "incline prone reverse fly": "incline_db_fly",
  "jump squat clusters": "kb_squat",
  "jump squat repeats": "kb_squat",
  "jump squats": "kb_goblet_jump_squat",
  "jump squats 40s squats": "landmine_hack_squat_jump",
  "kb clean and pull": "kb_clean",
  "kb controlled swing": "kb_single_arm_swing",
  "kb high pull": "kb_high_pull",
  "kb lateral raise": "dumbbell_lateral_raise",
  "kb overhead extensions": "cable_overhead_tricep_extension",
  "kb single arm row": "db_single_arm_row",
  "kb snatch": "kettlebell_snatch",
  "kb suitcase deadlift": "kb_suitcase_deadlift",
  "kb swing": "kb_single_arm_swing",
  "kb swing hip snap": "kb_hip_swing",
  "kb swing tempo": "kb_single_arm_swing",
  "kettlebell arnold press": "db_arnold_press",
  "kettlebell front raise": "db_front_raise",
  "kettlebell swings": "kb_single_arm_swing",
  "knee raise": "hanging_knee_raise",
  "knee raise holds short": "hanging_knee_raise",
  "knee tucks": "knee_tuck_crunches",
  "kneeling ab wheel": "kneeling_ab_wheel",
  "kneeling ab wheel diagonal rolls": "kneeling_ab_wheel",
  "kneeling ab wheel eccentric": "kneeling_ab_wheel",
  "ladder per side 3 2 1 clean jerk": "kb_clean",
  "ladder per side 3 2 1 clean press": "kb_clean",
  "ladder per side 3 2 1 clean push press": "kb_clean",
  "landmine split jerk ladder": "landmine_split_jerk",
  "landmine split jerk pop": "landmine_split_jerk",
  "lat pulldown": "neutral_grip_lat_pulldown",
  "lateral lunge": "db_side_lunge",
  "lateral raise": "db_lat_raise",
  "leg extension": "quad_extension",
  "leg extensions": "quad_extension",
  "leg press": "leg_press",
  "leg press calf drop set": "leg_press",
  "leg press calf pause": "leg_press",
  "leg press calf raise": "calf_raise",
  "leg press calf raise drop set": "calf_raise",
  "leg press calf raise iso jumps": "calf_raise",
  "leg press calf raise neutral": "calf_raise",
  "leg press calf raise toes out": "calf_raise",
  "leg press drop ladder": "leg_press",
  "leg press reps": "leg_press",
  "light barbell sissy squats": "kb_squat",
  "light crunches": "crunches",
  "low incline dumbbell delt fly": "incline_db_fly",
  "low to high cable fly": "cable_fly_low_to_high",
  "machine calf raise": "calf_raise",
  "mb crunches": "crunches",
  "mb sit up press outs": "sit_ups",
  "mb sit ups": "sit_ups",
  "mb slams": "slam_ball_slams",
  "mb toe touches": "hanging_toe_touch",
  "mb v sit twist": "sit_ups",
  "mid cable fly": "cable_machine_fly",
  "mixed grip pull ups": "pull_ups",
  "muscle ups": "muscle_ups",
  "narrow hack squats": "hack_squat",
  "negative pull ups": "pull_ups",
  "neutral grip pull ups": "neutral_grip_assisted_pull_up",
  "neutral grip pulldown": "neutral_grip_lat_pulldown",
  "neutral grip pullup": "neutral_grip_assisted_pull_up",
  "neutral grip row": "neutral_grip_t_bar_chest_supported_row",
  "neutral grip scap pulls": "pull_ups",
  "neutral grip t bar row": "neutral_grip_t_bar_chest_supported_row",
  "neutral grip t bar rows": "neutral_grip_t_bar_chest_supported_row",
  "neutral leg press": "leg_press",
  "neutral squats": "kb_squat",
  "next set 6 chin ups": "chin_ups",
  "oblique crunches": "crunches",
  "odd 4 6 burpees then squats till minute": "kb_squat",
  "overhead cable extensions": "cable_overhead_tricep_extension",
  "overhead db extensions": "cable_overhead_tricep_extension",
  "overhead press": "barbell_military_press",
  "overhead presses": "barbell_military_press",
  "overhead slams": "slam_ball_slams",
  "parallel bar tuck l sit hold": "sit_ups",
  "parallette l sit": "parallette_l_sit",
  "parallette pushup": "parallette_push_ups",
  "parallette tuck l sit": "parallette_l_sit",
  "partial back extensions": "roman_chair_back_extension",
  "pause back extension": "roman_chair_back_extension",
  "pause back squats": "kb_squat",
  "pause machine calf raise": "calf_raise",
  "paused barbell bench press": "barbell_flat_bench_press",
  "paused db incline press": "dumbbell_incline_press",
  "paused db rdls": "db_rdl",
  "paused decline press": "decline_bench_press",
  "paused dips": "dips",
  "paused ez skullcrushers": "ez_bar_skull_crusher",
  "paused incline press": "barbell_incline_bench_press",
  "paused pec deck": "pec_deck_fly",
  "paused squats": "kb_squat",
  "pec deck": "pec_deck_fly",
  "pec deck fly": "pec_deck_fly",
  "pendlay row": "barbell_row",
  "pendulum squat 1 5 reps": "kb_squat",
  "pendulum squats": "kb_squat",
  "per leg reverse lunges": "barbell_reverse_lunge",
  "per leg single leg press": "leg_press",
  "per leg split squats": "db_bulgarian_split_squat",
  "per side 5 4 3 snatches": "bb_snatch",
  "per side abductions": "hip_abductor",
  "per side alternating snatch": "bb_snatch",
  "per side bicycle crunches": "bicycle_crunches",
  "per side clean jerk": "kb_clean",
  "per side clean squat": "kb_squat",
  "per side cleans": "kb_clean",
  "per side db snatch": "bb_snatch",
  "per side dead start cleans": "kb_clean",
  "per side offset sit ups": "sit_ups",
  "per side push press": "barbell_push_press",
  "per side side bends": "roman_chair_side_bend",
  "per side skater bounds": "skater_bounds",
  "per side snatches": "kettlebell_snatch",
  "per side staggered rdls": "db_rdl",
  "per side twisting sit ups": "sit_ups",
  "per side weighted bends": "roman_chair_side_bend",
  "pistol box squat": "kb_squat",
  "plank": "plank",
  "plank hold": "plank",
  "plank holds": "plank",
  "power clean": "power_clean",
  "pronated pullup": "pull_ups",
  "prone rear delt fly": "db_fly",
  "pull 20s easy": "pull_ups",
  "pull 30s easy": "pull_ups",
  "pull 40s easy": "pull_ups",
  "pull ups": "pull_ups",
  "push press": "barbell_push_press",
  "push press per side": "barbell_push_press",
  "push presses": "barbell_push_press",
  "pushdowns": "cable_rope_tricep_pushdown",
  "rack pulls heavy": "rack_pull",
  "rack rdls": "db_rdl",
  "rdls": "smith_machine_rdl",
  "rdls per leg": "smith_machine_rdl",
  "rdls per side": "smith_machine_rdl",
  "reactive drop squats": "kb_squat",
  "rear delt fly": "cable_rear_delt_fly",
  "rear foot flat split squat": "kb_squat",
  "renegade row": "db_renegade_rows",
  "reverse hack squats": "reverse_hack_squat",
  "reverse lunge": "barbell_reverse_lunge",
  "reverse lunges": "barbell_reverse_lunge",
  "reverse lunges per leg": "barbell_reverse_lunge",
  "ring dip": "dips",
  "ring front plank": "plank",
  "ring muscle up transition practice": "muscle_ups",
  "romanian deadlift": "smith_machine_rdl",
  "rope cable curl": "cable_rope_curl",
  "rope overhead extensions": "cable_overhead_tricep_extension",
  "rope pressdown": "cable_rope_tricep_pushdown",
  "rope pushdowns": "cable_rope_tricep_pushdown",
  "rotational throws": "slam_ball_rotational_throw",
  "round 1 band squat jumps": "kb_squat",
  "rows": "barbell_row",
  "russian twists": "medicine_ball_russian_twists",
  "seated arnold press": "db_arnold_press",
  "seated calf raise": "calf_raise",
  "seated calf raise machine": "calf_raise",
  "seated db calf raise": "calf_raise",
  "seated dumbbell curl": "dumbbell_curl",
  "seated dumbbell lateral raise": "dumbbell_lateral_raise",
  "seated dumbbell shoulder press": "dumbbell_shoulder_press",
  "seated front raise": "db_front_raise",
  "seated row": "cable_rope_row",
  "shoulder press": "dumbbell_shoulder_press",
  "side bends": "roman_chair_side_bend",
  "side plank": "side_plank",
  "side plank l": "side_plank",
  "side plank r": "side_plank",
  "side plank with hip tap": "side_plank",
  "side plank with reach": "side_plank",
  "side plank with top arm reach": "side_plank",
  "side to side waves": "battle_rope_side_to_side_slams",
  "single arm cable delt fly": "db_fly",
  "single arm cable lateral raise": "cable_lateral_raise",
  "single arm db rows": "db_single_arm_row",
  "single arm dumbbell row": "db_single_arm_row",
  "single arm kb row": "db_single_arm_row",
  "single arm landmine press": "landmine_push_press",
  "single arm landmine push press": "landmine_push_press",
  "single arm rear delt fly": "db_fly",
  "single arm row": "db_single_arm_row",
  "single arm swings": "kb_single_arm_swing",
  "single leg calf raise machine": "calf_raise",
  "single leg db calf raise": "calf_raise",
  "single leg press calf raise": "calf_raise",
  "single leg rdl reach": "db_single_leg_rdl",
  "sissy squat 1 reps": "kb_squat",
  "sissy squats": "kb_squat",
  "sit ups": "sit_ups",
  "sit ups w plate": "sit_ups",
  "skater squat": "kb_squat",
  "slams": "slam_ball_slams",
  "slow eccentric crunches": "crunches",
  "slow hanging knee raise": "hanging_knee_raise",
  "slow pull": "pull_ups",
  "small squat hops": "kb_squat",
  "smith back squat": "smith_machine_back_squat",
  "smith front squat": "db_front_squat",
  "smith rdl": "smith_machine_rdl",
  "smith rdl or plate loaded rdl machine": "smith_machine_rdl",
  "smith rdl or seated leg curl": "db_rdl",
  "smith split squat": "kb_squat",
  "snatch": "kettlebell_snatch",
  "snatch grip push press": "bb_snatch",
  "snatch high pulls": "kb_high_pull",
  "snatches": "kettlebell_snatch",
  "split jerk": "barbell_split_jerk",
  "split jerks": "barbell_split_jerk",
  "split squat jump repeats": "split_squat_jump",
  "split squat jumps": "split_squat_jump",
  "split squats per leg": "db_bulgarian_split_squat",
  "squat 2 pulse stand": "kb_squat",
  "squat clean": "kb_squat",
  "squat hold": "kb_squat",
  "squat jump": "landmine_hack_squat_jump",
  "squat jumps": "landmine_hack_squat_jump",
  "squat jumps 40s squats": "landmine_hack_squat_jump",
  "squat pops": "squat_pop_stick",
  "squat reverse lunge": "kb_squat",
  "squat to press": "slam_ball_squat_press",
  "squat to rows": "kb_squat",
  "squat to stand": "kb_squat",
  "squats": "kb_squat",
  "squats 10s hold 6 pulses": "kb_squat",
  "squats 5 pulses": "kb_squat",
  "standing barbell calf raise": "calf_raise",
  "standing calf raise": "calf_raise",
  "standing calf raise machine": "calf_raise",
  "standing db calf raise": "calf_raise",
  "standing dumbbell shoulder press": "dumbbell_shoulder_press",
  "standing rollouts": "ab_wheel_standing_rollout",
  "step up pops": "plyo_box_step_up_pops",
  "steps total walking lunges": "walking_lunges",
  "strict overhead press": "barbell_military_press",
  "strict parallel bar dips": "dips",
  "strict press": "barbell_military_press",
  "strict pullup": "pull_ups",
  "sumo deadlifts": "barbell_sumo_deadlift",
  "supported crunches": "crunches",
  "t bar rows": "t-bar_row_machine",
  "tempo abduction": "hip_abductor",
  "tempo back squat": "smith_machine_back_squat",
  "tempo dips with band": "dips",
  "tempo front squat": "barbell_front_squat",
  "tempo hip thrust": "barbell_hip_thrust",
  "tempo neutral rows": "neutral_grip_t_bar_chest_supported_row",
  "tempo rdls": "smith_machine_rdl",
  "tempo zercher squat": "kb_squat",
  "tire flips": "tire_flip",
  "toes to bar": "hanging_toe_touch",
  "top half machine crunch pulses": "crunches",
  "top isometric chin up hold": "chin_ups",
  "trap bar deadlift pop": "trap_bar_deadlift",
  "trap bar deadlifts": "trap_bar_deadlift",
  "trap bar jumps": "trap_bar_squat_jump",
  "tricep pushdowns": "cable_rope_tricep_pushdown",
  "triple extension heave": "landmine_triple_extension_heave",
  "tuck l sit hold": "sit_ups",
  "v ups": "v_ups",
  "wall sit": "sit_ups",
  "weighted back extensions": "roman_chair_weighted_back_extension",
  "weighted box jumps": "plyo_box_jump",
  "weighted chin up drop ladder": "chin_ups",
  "weighted chin ups": "chin_ups",
  "weighted dips": "dips",
  "weighted eccentric dip": "dips",
  "weighted extensions": "roman_chair_weighted_back_extension",
  "weighted neutral pull ups": "pull_ups",
  "weighted pull ups": "pull_ups",
  "weighted sissy squats": "kb_squat",
  "weighted sit ups": "sit_ups",
  "weighted step up pops": "plyo_box_step_up_pops",
  "wide grip pull ups": "wide_grip_assisted_pull_up",
  "wide grip row": "wide_grip_t_bar_chest_supported_row",
  "wide grip rows": "wide_grip_t_bar_chest_supported_row",
  "wide grip t bar row": "wide_grip_t_bar_chest_supported_row",
  "wide grip t bar rows": "wide_grip_t_bar_chest_supported_row",
  "wide hack squats": "hack_squat",
  "wide stance squats": "kb_squat",
  "zercher box squat": "kb_squat",
  "zercher pause squat": "kb_squat",
};
